Repository yongiCorp/Server, pull requests merged in 2024-02, with the labels that each got.

#33 ✨ [Feat] 사용자 아바타의 구매 아이템 조회
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/controller/ItemController.java
  src/main/java/com/brandol/converter/ItemConverter.java
  src/main/java/com/brandol/dto/response/MyItemResponseDto.java
  src/main/java/com/brandol/repository/ItemsRepository.java
  src/main/java/com/brandol/repository/MyItemRepository.java
  src/main/java/com/brandol/service/ItemService.java
Labels: :sparkles: Feat

#32 Feat/11 검색 메인 페이지 조회 API 구현
  .gitignore
  src/main/java/com/brandol/aws/AmazonS3Manager.java
  src/main/java/com/brandol/config/AmazonConfig.java
  src/main/java/com/brandol/controller/SearchController.java
  src/main/java/com/brandol/converter/SearchConverter.java
  src/main/java/com/brandol/domain/Contents.java
  src/main/java/com/brandol/dto/response/SearchResponseDto.java
  src/main/java/com/brandol/repository/BrandRepository.java
  src/main/java/com/brandol/repository/ContentImageRepository.java
  src/main/java/com/brandol/repository/ContentsRepository.java
  src/main/java/com/brandol/repository/ItemsRepository.java
  src/main/java/com/brandol/repository/MemberRepository.java
  src/main/java/com/brandol/service/BrandService.java
  src/main/java/com/brandol/service/SearchService.java
  src/main/java/com/brandol/validation/annotation/ExistBrand.java
  src/main/java/com/brandol/validation/validator/BrandExistValidator.java
Labels: :sparkles: Feat

#35 ✨ [Feat] 아이템 착용
  src/main/java/com/brandol/controller/ItemController.java
  src/main/java/com/brandol/domain/mapping/MyItem.java
  src/main/java/com/brandol/dto/request/MyItemRequestDto.java
  src/main/java/com/brandol/repository/MyItemRepository.java
  src/main/java/com/brandol/service/ItemService.java
Labels: :sparkles: Feat

#36 Feat/31 브랜트 커뮤니티 조회/생성 구현
  src/main/java/com/brandol/controller/BrandController.java
  src/main/java/com/brandol/converter/BrandConverter.java
  src/main/java/com/brandol/domain/mapping/CommunityImage.java
  src/main/java/com/brandol/dto/request/BrandRequestDto.java
  src/main/java/com/brandol/dto/response/BrandResponseDto.java
  src/main/java/com/brandol/repository/CommunityImageRepository.java
  src/main/java/com/brandol/repository/CommunityRepository.java
  src/main/java/com/brandol/repository/ContentsRepository.java
  src/main/java/com/brandol/service/BrandService.java
Labels: :sparkles: Feat

#38 사용자 포인트 미션 조회
  src/main/java/com/brandol/controller/HealthController.java
  src/main/java/com/brandol/controller/MemberMissionController.java
  src/main/java/com/brandol/converter/MemberMissionConverter.java
  src/main/java/com/brandol/dto/response/MemberMainPageResponse.java
  src/main/java/com/brandol/dto/response/MemberMissionResponseDto.java
  src/main/java/com/brandol/repository/MemberMissionRepository.java
  src/main/java/com/brandol/repository/MissionRepository.java
  src/main/java/com/brandol/service/MemberMissionService.java
Labels: :sparkles: Feat

#39 Feat/30 검색 더보기 페이지 조회 API
  src/main/java/com/brandol/controller/SearchController.java
  src/main/java/com/brandol/converter/SearchConverter.java
  src/main/java/com/brandol/domain/enums/ItemPart.java
  src/main/java/com/brandol/dto/response/SearchResponseDto.java
  src/main/java/com/brandol/repository/BrandRepository.java
  src/main/java/com/brandol/repository/ContentsRepository.java
  src/main/java/com/brandol/repository/ItemsRepository.java
  src/main/java/com/brandol/repository/MemberRepository.java
  src/main/java/com/brandol/service/SearchService.java
Labels: :sparkles: Feat

#45 환경변수 설정
  .gitignore
  src/main/java/com/brandol/controller/MemberController.java
  src/main/resources/application-aws.yml
Labels: :recycle: Refactor

#41 스프링 시큐리티, jwt 설정
  build.gradle
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/config/SecurityConfig.java
  src/main/java/com/brandol/config/security/JwtAccessDeniedHandler.java
  src/main/java/com/brandol/config/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/brandol/config/security/JwtAuthenticationFilter.java
  src/main/java/com/brandol/config/security/JwtProvider.java
  src/main/java/com/brandol/config/security/PrincipalDetails.java
  src/main/java/com/brandol/config/security/PrincipalDetailsService.java
  src/main/java/com/brandol/config/security/TokenDto.java
  src/main/java/com/brandol/controller/AuthController.java
  src/main/java/com/brandol/converter/MemberConverter.java
  src/main/java/com/brandol/domain/Member.java
  src/main/java/com/brandol/domain/enums/Role.java
  src/main/java/com/brandol/dto/request/AuthRequestDto.java
  src/main/java/com/brandol/repository/MemberRepository.java
  src/main/java/com/brandol/service/AuthService.java
Labels: :sparkles: Feat

#46 ✨ [Feat] 소셜 로그인
  build.gradle
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/config/SecurityConfig.java
  src/main/java/com/brandol/config/security/JwtAccessDeniedHandler.java
  src/main/java/com/brandol/config/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/brandol/config/security/JwtAuthenticationFilter.java
  src/main/java/com/brandol/config/security/JwtProvider.java
  src/main/java/com/brandol/config/security/PrincipalDetailsService.java
  src/main/java/com/brandol/controller/AuthController.java
  src/main/java/com/brandol/converter/AgreementConverter.java
  src/main/java/com/brandol/converter/MemberConverter.java
  src/main/java/com/brandol/domain/Member.java
  src/main/java/com/brandol/domain/enums/Provider.java
  src/main/java/com/brandol/dto/request/AuthRequestDto.java
  src/main/java/com/brandol/dto/response/AuthResponseDto.java
  src/main/java/com/brandol/repository/AgreementRepository.java
  src/main/java/com/brandol/repository/MemberRepository.java
  src/main/java/com/brandol/repository/TermRepository.java
  src/main/java/com/brandol/service/AuthService.java
  src/main/java/com/brandol/service/MemberService.java
  src/main/java/com/brandol/validation/annotation/ExistNickname.java
  src/main/java/com/brandol/validation/validator/NicknameExistValidator.java
Labels: :sparkles: Feat

#47 문서 수정
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/controller/AuthController.java
  src/main/java/com/brandol/controller/BrandController.java
  src/main/java/com/brandol/controller/HealthController.java
  src/main/java/com/brandol/controller/ItemController.java
  src/main/java/com/brandol/controller/MemberBrandController.java
  src/main/java/com/brandol/controller/MemberController.java
  src/main/java/com/brandol/controller/MemberMissionController.java
  src/main/java/com/brandol/controller/SearchController.java
  src/main/java/com/brandol/converter/MemberConverter.java
  src/main/java/com/brandol/domain/Member.java
  src/main/java/com/brandol/repository/MemberBrandRepository.java
  src/main/java/com/brandol/repository/MemberRepository.java
  src/main/java/com/brandol/service/MemberService.java
  src/main/resources/application.yml
Labels: :memo: Docs

#55 [Feat/53] 멤버 작성 글/ 댓글 목록 조회 + 댓글 등록 기능 추가
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/config/SecurityConfig.java
  src/main/java/com/brandol/controller/BrandController.java
  src/main/java/com/brandol/controller/CommentController.java
  src/main/java/com/brandol/controller/MemberController.java
  src/main/java/com/brandol/converter/CommentConverter.java
  src/main/java/com/brandol/converter/MemberConverter.java
  src/main/java/com/brandol/domain/Fandom.java
  src/main/java/com/brandol/domain/Member.java
  src/main/java/com/brandol/dto/request/CommentRequestDto.java
  src/main/java/com/brandol/dto/response/MemberResponseDto.java
  src/main/java/com/brandol/repository/CommunityCommentRepository.java
  src/main/java/com/brandol/repository/ContentsCommentRepository.java
  src/main/java/com/brandol/repository/FandomCommentRepository.java
  src/main/java/com/brandol/service/CommentService.java
  src/main/java/com/brandol/service/MemberService.java
Labels: :sparkles: Feat

#59 ✨ [Feat] 아바타 이미지 저장
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/aws/AmazonS3Manager.java
  src/main/java/com/brandol/controller/ItemController.java
  src/main/java/com/brandol/domain/Member.java
  src/main/java/com/brandol/domain/enums/ItemPart.java
  src/main/java/com/brandol/dto/request/MyItemRequestDto.java
  src/main/java/com/brandol/service/ItemService.java
Labels: :sparkles: Feat

#60 브랜드 관련 미션 상태 확인
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/brandol/config/SecurityConfig.java
  src/main/java/com/brandol/controller/MemberBrandController.java
  src/main/java/com/brandol/domain/enums/MissionStatus.java
  src/main/java/com/brandol/domain/mapping/MemberMission.java
  src/main/java/com/brandol/repository/MemberMissionRepository.java
  src/main/java/com/brandol/service/MemberMissionService.java
Labels: :sparkles: Feat

#64 기존 아바타 이미지 S3에서 삭제 후 새로운 아바타 저장
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/aws/AmazonS3Manager.java
  src/main/java/com/brandol/config/AmazonConfig.java
  src/main/java/com/brandol/service/ItemService.java
  src/main/resources/application-aws.yml
Labels: :recycle: Refactor

#66 필수 약관 동의 예외 처리
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/controller/AuthController.java
  src/main/java/com/brandol/repository/TermRepository.java
  src/main/java/com/brandol/service/AuthService.java
Labels: :recycle: Refactor

#69 대댓글 작성 API 구현 완료 + 댓글,대댓글 작성시 comments(댓글수) 업데이트 구현완료
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/controller/CommentController.java
  src/main/java/com/brandol/controller/MemberBrandController.java
  src/main/java/com/brandol/controller/MemberMissionController.java
  src/main/java/com/brandol/domain/Contents.java
  src/main/java/com/brandol/domain/Fandom.java
  src/main/java/com/brandol/domain/mapping/Community.java
  src/main/java/com/brandol/domain/mapping/CommunityComment.java
  src/main/java/com/brandol/domain/mapping/ContentsComment.java
  src/main/java/com/brandol/domain/mapping/FandomComment.java
  src/main/java/com/brandol/dto/request/MyItemRequestDto.java
  src/main/java/com/brandol/repository/CommunityCommentRepository.java
  src/main/java/com/brandol/repository/ContentsCommentRepository.java
  src/main/java/com/brandol/repository/FandomCommentRepository.java
  src/main/java/com/brandol/service/CommentService.java
Labels: :sparkles: Feat

#71 ✨ [Feat] 회원 탈퇴
  src/main/java/com/brandol/controller/AuthController.java
  src/main/java/com/brandol/domain/Member.java
  src/main/java/com/brandol/service/AuthService.java
Labels: :sparkles: Feat

#74 ✨ [Feat] 다른 멤버의 아바타 및 닉네임 조회
  src/main/java/com/brandol/controller/MemberController.java
  src/main/java/com/brandol/converter/MemberConverter.java
  src/main/java/com/brandol/dto/response/MemberResponseDto.java
  src/main/java/com/brandol/service/MemberService.java
Labels: :sparkles: Feat

#76 브랜드 미션 상태 확인 코드
  src/main/java/com/brandol/controller/MemberBrandController.java
  src/main/java/com/brandol/controller/MemberMissionController.java
  src/main/java/com/brandol/converter/MemberMissionConverter.java
  src/main/java/com/brandol/dto/response/MemberMissionResponseDto.java
  src/main/java/com/brandol/repository/MemberMissionRepository.java
  src/main/java/com/brandol/repository/MissionRepository.java
  src/main/java/com/brandol/service/MemberMissionService.java
Labels: :recycle: Refactor

#78 각 게시글에 대한 댓글 전체 조회 API
  src/main/java/com/brandol/controller/CommentController.java
  src/main/java/com/brandol/converter/CommentConverter.java
  src/main/java/com/brandol/dto/response/CommentResponseDto.java
  src/main/java/com/brandol/repository/CommunityCommentRepository.java
  src/main/java/com/brandol/repository/ContentsCommentRepository.java
  src/main/java/com/brandol/repository/FandomCommentRepository.java
  src/main/java/com/brandol/service/CommentService.java
Labels: :sparkles: Feat

#84 다른 회원의 아바타 검색 - 해당 회원의 브랜드리스트, 착용 아이템, 작성한 글 조회
  src/main/java/com/brandol/controller/ItemController.java
  src/main/java/com/brandol/converter/AvatarConverter.java
  src/main/java/com/brandol/converter/ItemConverter.java
  src/main/java/com/brandol/dto/response/AvatarResponseDto.java
  src/main/java/com/brandol/repository/CommunityImageRepository.java
  src/main/java/com/brandol/repository/CommunityRepository.java
  src/main/java/com/brandol/repository/MemberRepository.java
  src/main/java/com/brandol/service/AvatarService.java
  src/main/java/com/brandol/service/ItemService.java
Labels: :sparkles: Feat

#83 [Feat/75] 아이템 정보 조회 api 구현
  src/main/java/com/brandol/controller/ItemController.java
  src/main/java/com/brandol/converter/ItemConverter.java
  src/main/java/com/brandol/dto/response/ItemResponseDto.java
  src/main/java/com/brandol/repository/ItemsRepository.java
  src/main/java/com/brandol/service/ItemService.java
Labels: :sparkles: Feat

#88 아바타 아이템 착용 요청온 wearingItemIdList를 MyItem id에서 Item의 id로 수정
  src/main/java/com/brandol/controller/ItemController.java
  src/main/java/com/brandol/dto/request/MyItemRequestDto.java
  src/main/java/com/brandol/repository/MyItemRepository.java
  src/main/java/com/brandol/service/ItemService.java
Labels: :recycle: Refactor

#92 회원가입 시 아바타 기본 이미지 수정, 아바타 조회
  src/main/java/com/brandol/controller/ItemController.java
  src/main/java/com/brandol/service/AuthService.java
  src/main/java/com/brandol/service/AvatarService.java
Labels: :recycle: Refactor

#94 Swagger 문서 수정
  src/main/java/com/brandol/controller/MemberMissionController.java
Labels: :memo: Docs

#98 Refactor/97 @RequestParam memberId -> 인증객체 id 추출 방식 변경
  src/main/java/com/brandol/controller/BrandController.java
  src/main/java/com/brandol/controller/CommentController.java
  src/main/java/com/brandol/controller/CommunityController.java
  src/main/java/com/brandol/controller/ContentsController.java
  src/main/java/com/brandol/controller/FandomController.java
Labels: :recycle: Refactor

#100 닉네임 변경
  src/main/java/com/brandol/controller/AuthController.java
  src/main/java/com/brandol/converter/MemberConverter.java
  src/main/java/com/brandol/domain/Member.java
  src/main/java/com/brandol/dto/request/AuthRequestDto.java
  src/main/java/com/brandol/dto/response/AuthResponseDto.java
  src/main/java/com/brandol/service/AuthService.java
  src/main/java/com/brandol/validation/annotation/ExistNickname.java
Labels: :sparkles: Feat

#103 ✨ [Feat] 마이페이지 사용자 정보 조회(닉네임, 아바타, 포인트)
  src/main/java/com/brandol/controller/AuthController.java
  src/main/java/com/brandol/converter/MemberConverter.java
  src/main/java/com/brandol/dto/response/AuthResponseDto.java
  src/main/java/com/brandol/service/AuthService.java
Labels: :sparkles: Feat

#106 ♻️ [Refactor] 아바타 보유아이템 조회 시, 착용 전 아이템 이미지와 착용 아이템 이미지 조회
  src/main/java/com/brandol/controller/AuthController.java
  src/main/java/com/brandol/controller/ItemController.java
  src/main/java/com/brandol/converter/AvatarConverter.java
  src/main/java/com/brandol/domain/Items.java
  src/main/java/com/brandol/dto/response/MyItemResponseDto.java
Labels: :recycle: Refactor

#108 ♻️ [Refactor] 아바타 아이템 착용 id가 null일 때는 다 false로 바꿔주는 코드 리팩토링
  src/main/java/com/brandol/dto/request/MyItemRequestDto.java
  src/main/java/com/brandol/service/ItemService.java
Labels: :recycle: Refactor

#109 [Feature] 아이템 구매 API
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/controller/ItemController.java
  src/main/java/com/brandol/converter/ItemConverter.java
  src/main/java/com/brandol/domain/PointHistory.java
  src/main/java/com/brandol/domain/enums/HistoryType.java
  src/main/java/com/brandol/repository/PointHistoryRepository.java
  src/main/java/com/brandol/service/ItemService.java
  src/main/java/com/brandol/service/PointHistoryService.java
Labels: :sparkles: Feat

#112 [Feature]설문조사 미션 도전 API
  src/main/java/com/brandol/controller/MemberMissionController.java
  src/main/java/com/brandol/converter/MemberMissionConverter.java
  src/main/java/com/brandol/domain/SurveyExample.java
  src/main/java/com/brandol/domain/SurveyQuestion.java
  src/main/java/com/brandol/domain/enums/QuestionType.java
  src/main/java/com/brandol/domain/mapping/SurveyAnswer.java
  src/main/java/com/brandol/dto/response/MemberMissionResponseDto.java
  src/main/java/com/brandol/repository/SurveyExampleRepository.java
  src/main/java/com/brandol/repository/SurveyQuestionRepository.java
  src/main/java/com/brandol/service/SurveyService.java
Labels: :sparkles: Feat

#115 설문조사 성공 API
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/controller/MemberMissionController.java
  src/main/java/com/brandol/dto/request/MemberMissionRequestDto.java
  src/main/java/com/brandol/repository/SurveyAnswerRepository.java
  src/main/java/com/brandol/service/MemberMissionService.java
  src/main/java/com/brandol/service/PointHistoryService.java
  src/main/java/com/brandol/service/SurveyService.java
Labels: :sparkles: Feat

#118 Refactor/117 Brand -> brand로 수정
  src/main/java/com/brandol/repository/BrandRepository.java
Labels: :recycle: Refactor

#126 Refactor/125 홈페이지 조회 시 브랜드 리스트에 brandDescription 추가
  src/main/java/com/brandol/converter/MemberConverter.java
  src/main/java/com/brandol/dto/response/MemberResponseDto.java
Labels: :recycle: Refactor

#128 Refactor/127 브랜드 검색 시 특정 브랜드를 조회 대상에서 제외
  src/main/java/com/brandol/repository/BrandRepository.java
  src/main/java/com/brandol/service/SearchService.java
Labels: :recycle: Refactor

#124 회원가입 시 성별에 따라 아바타 기본 아이템 장착
  src/main/java/com/brandol/service/AuthService.java
  src/main/resources/application.yml
Labels: :recycle: Refactor

#130 Feat/122 게시판 미션 도전 API
  src/main/java/com/brandol/controller/MemberMissionController.java
  src/main/java/com/brandol/domain/enums/MissionType.java
  src/main/java/com/brandol/repository/CommunityRepository.java
  src/main/java/com/brandol/service/MemberMissionService.java
Labels: :sparkles: Feat

#132 Feat/122 게시판 미션 성공 API
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/controller/BrandController.java
  src/main/java/com/brandol/controller/MemberMissionController.java
  src/main/java/com/brandol/repository/MemberBrandRepository.java
  src/main/java/com/brandol/repository/MissionRepository.java
  src/main/java/com/brandol/service/MemberMissionService.java
Labels: :sparkles: Feat

#134 Feat/133 포인트 내역 조회 API
  src/main/java/com/brandol/controller/PointHistoryController.java
  src/main/java/com/brandol/converter/PointHistoryConverter.java
  src/main/java/com/brandol/dto/response/PointHistoryResponseDto.java
  src/main/java/com/brandol/repository/PointHistoryRepository.java
  src/main/java/com/brandol/service/PointHistoryService.java
Labels: :sparkles: Feat

#139 서브배너 탐색 범위 조정 기존:최신 컨텐츠(전체범위)10건 -> 변경:최신 컨텐츠(컨텐츠 중 이벤트에서만)10건
  src/main/java/com/brandol/repository/ContentsRepository.java
  src/main/java/com/brandol/service/MemberService.java
Labels: :bug: Fix

#144 탈퇴한 회원(비활성화된) 회원 로그인 예외 처리
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/service/AuthService.java
Labels: :bug: Fix

#141 JWT 토큰 검증 시 Exception 예외 처리
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/config/SecurityConfig.java
  src/main/java/com/brandol/config/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/brandol/config/security/JwtProvider.java
Labels: :recycle: Refactor

#147 ♻️ [Refactor] 회원 기본 포인트 0 -> 1000 으로 수정
  src/main/java/com/brandol/converter/MemberConverter.java
  src/main/java/com/brandol/domain/Member.java
Labels: :recycle: Refactor

#152 Feat/143 채팅방 생성, 메시지 전송, 메시지 조회 기능 구현완료
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/controller/ChatController.java
  src/main/java/com/brandol/converter/ChatConverter.java
  src/main/java/com/brandol/domain/ChatMessages.java
  src/main/java/com/brandol/dto/request/ChatMessageRequestDto.java
  src/main/java/com/brandol/dto/response/ChatResponseDto.java
  src/main/java/com/brandol/repository/ChatMessageRepository.java
  src/main/java/com/brandol/repository/ChatRoomsRepository.java
  src/main/java/com/brandol/service/ChatService.java
Labels: :sparkles: Feat

#148 Feat/146 직접 검색 api 구현
  src/main/java/com/brandol/controller/SearchController.java
  src/main/java/com/brandol/repository/BrandRepository.java
  src/main/java/com/brandol/repository/ContentsRepository.java
  src/main/java/com/brandol/repository/ItemsRepository.java
  src/main/java/com/brandol/repository/MemberRepository.java
  src/main/java/com/brandol/service/SearchService.java
Labels: :sparkles: Feat

#150 토큰 유효시간 임시 수정
  src/main/java/com/brandol/config/security/JwtProvider.java
Labels: :recycle: Refactor

#153 검색 시 브랜드 관리자는 유저 조회 안되도록 수정
  src/main/java/com/brandol/repository/MemberRepository.java
Labels: :recycle: Refactor

#160 Refactor/156 메인배너 조회시 '일반' 브랜드는 제외하도록 수정
  src/main/java/com/brandol/repository/BrandRepository.java
Labels: :recycle: Refactor
