Repository yongiCorp/Server, pull requests merged in 2024-01, with the labels that each got.

#2 Feat/1 초기 설정 및 엔티티 생성
  build.gradle
  src/main/java/com/brandol/BrandolApplication.java
  src/main/java/com/brandol/apiPayload/ApiResponse.java
  src/main/java/com/brandol/apiPayload/code/BaseCode.java
  src/main/java/com/brandol/apiPayload/code/ReasonDto.java
  src/main/java/com/brandol/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/brandol/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/brandol/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/brandol/apiPayload/exception/GeneralException.java
  src/main/java/com/brandol/domain/Block.java
  src/main/java/com/brandol/domain/Brand.java
  src/main/java/com/brandol/domain/ChatMessages.java
  src/main/java/com/brandol/domain/ChatRooms.java
  src/main/java/com/brandol/domain/Contents.java
  src/main/java/com/brandol/domain/ContentsImage.java
  src/main/java/com/brandol/domain/Fandom.java
  src/main/java/com/brandol/domain/Items.java
  src/main/java/com/brandol/domain/Member.java
  src/main/java/com/brandol/domain/PointHistory.java
  src/main/java/com/brandol/domain/Term.java
  src/main/java/com/brandol/domain/common/BaseEntity.java
  src/main/java/com/brandol/domain/enums/CommunityType.java
  src/main/java/com/brandol/domain/enums/ContentsType.java
  src/main/java/com/brandol/domain/enums/FandomType.java
  src/main/java/com/brandol/domain/enums/Gender.java
  src/main/java/com/brandol/domain/enums/ItemPart.java
  src/main/java/com/brandol/domain/enums/MemberListStatus.java
  src/main/java/com/brandol/domain/enums/TermType.java
  src/main/java/com/brandol/domain/enums/UserStatus.java
  src/main/java/com/brandol/domain/mapping/Agreement.java
  src/main/java/com/brandol/domain/mapping/Community.java
  src/main/java/com/brandol/domain/mapping/CommunityComment.java
  src/main/java/com/brandol/domain/mapping/CommunityLikes.java
  src/main/java/com/brandol/domain/mapping/ContentsComment.java
  src/main/java/com/brandol/domain/mapping/ContentsLikes.java
  src/main/java/com/brandol/domain/mapping/FandomComment.java
  src/main/java/com/brandol/domain/mapping/FandomLikes.java
  src/main/java/com/brandol/domain/mapping/MemberBrandList.java
  src/main/java/com/brandol/domain/mapping/MyItem.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :sparkles: Feat

#8 👷 CI/CD 파이프라인 생성
  .ebextensions/00-makeFiles.config
  .ebextensions/01-set-timezone.config
  .github/workflows/deploy.yml
  .platform/nginx.conf
  Procfile
  build.gradle
  src/main/java/com/brandol/controller/HealthController.java
  src/main/resources/application.yml
Labels: :sparkles: Feat, :construction_worker: Ci

#15 미션 엔티티 생성
  src/main/java/com/brandol/domain/Mission.java
  src/main/java/com/brandol/domain/enums/MissionStatus.java
  src/main/java/com/brandol/domain/enums/MissionType.java
  src/main/java/com/brandol/domain/mapping/MemberMission.java
Labels: :sparkles: Feat

#20 Feat/18 FandomImage 엔티티 추가 및 팬덤 페이지 Response 사진 URL 추가
  src/main/java/com/brandol/domain/FandomImage.java
  src/main/java/com/brandol/dto/subDto/BrandFandomBody.java
  src/main/java/com/brandol/repository/FandomImageRepository.java
  src/main/java/com/brandol/service/BrandService.java
Labels: :sparkles: Feat

#21 AWS S3 재설정
  .gitignore
  src/main/java/com/brandol/aws/AmazonS3Manager.java
  src/main/java/com/brandol/config/AmazonConfig.java
  src/main/java/com/brandol/service/BrandService.java
  src/main/resources/application.yml
Labels: :recycle: Refactor

#27 Refactor/25 멤버 메인페이지, 팬덤 페이지 응답 DTO 리팩토링
  src/main/java/com/brandol/controller/BrandController.java
  src/main/java/com/brandol/controller/MemberBrandController.java
  src/main/java/com/brandol/controller/MemberController.java
  src/main/java/com/brandol/converter/BrandConverter.java
  src/main/java/com/brandol/converter/MemberConverter.java
  src/main/java/com/brandol/domain/Contents.java
  src/main/java/com/brandol/dto/request/AddBrandRequest.java
  src/main/java/com/brandol/dto/request/AddMemberBrandRequest.java
  src/main/java/com/brandol/dto/request/BrandRequestDto.java
  src/main/java/com/brandol/dto/request/MemberBrandRequestDto.java
  src/main/java/com/brandol/dto/response/BrandCommonHeaderResponse.java
  src/main/java/com/brandol/dto/response/BrandFandomBodyResponse.java
  src/main/java/com/brandol/dto/response/BrandResponseDto.java
  src/main/java/com/brandol/dto/response/MemberResponseDto.java
  src/main/java/com/brandol/dto/subDto/BrandFandomBody.java
  src/main/java/com/brandol/dto/subDto/BrandHeader.java
  src/main/java/com/brandol/dto/subDto/BrandList.java
  src/main/java/com/brandol/dto/subDto/MainBanners.java
  src/main/java/com/brandol/dto/subDto/SubBanners.java
  src/main/java/com/brandol/repository/ContentImageRepository.java
  src/main/java/com/brandol/service/BrandService.java
  src/main/java/com/brandol/service/ContentsService.java
  src/main/java/com/brandol/service/MemberBrandService.java
  src/main/java/com/brandol/service/MemberService.java
Labels: :recycle: Refactor

#29 브랜드 콘텐츠 조회 API 구현 완료
  src/main/java/com/brandol/controller/BrandController.java
  src/main/java/com/brandol/converter/BrandConverter.java
  src/main/java/com/brandol/domain/Contents.java
  src/main/java/com/brandol/dto/response/BrandResponseDto.java
  src/main/java/com/brandol/repository/ContentsRepository.java
  src/main/java/com/brandol/service/BrandService.java
Labels: :sparkles: Feat
